### ISSUE TITLE
Run Error

### ISSUE THREAD

**Issue by mahxn0** [Myzhar/opencv_gstreamer_appsink#1]
thank you for your code,there are compile success,but
when i run, return error
 ---- Segmentation fault (core dumped)
what happened,can you help it .thank you

**Comment by Myzhar** [comment]
Can you give me more information about your configuration?
Operating system, GStreamer version, ...

**Comment by mahxn0** [comment]
build on ubuntu16.04  opencv3.2.0 and gstream1.0 
there are the commands for installed gst i uesd：
sudo apt-get install gstreamer1.0-tools gstreamer1.0-alsa gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav
sudo apt-get install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-good1.0-dev libgstreamer-plugins-bad1.0-dev
//test.cpp
`#include "gst_appsink_opencv.hpp"

#include <opencv2/highgui/highgui.hpp>
#include <string>

#include <gst/gst.h>

using namespace std;

int main(int argc, char *argv[])
{
    gst_init( &argc, &argv );

    string pipeline = "v4l2src device=/dev/video0 ! "
                      "video/x-raw,format=I420,framerate=30/1,width=1280,height=720 ! "
                      "videoconvert";

    GstSinkOpenCV* ocvAppsink = GstSinkOpenCV::Create( pipeline, 5, 15, GstSinkOpenCV::DEBUG_NONE );

    while(1)
    {
        // Getting last frame from appsink
        cv::Mat frame = ocvAppsink->getLastFrame();

        if( !frame.empty() )
        {
            cv::imshow( "Frame", frame );
        }

        if( cv::waitKey(5) == 'q' )
        {
            break;
        }
    }

    delete ocvAppsink;
}
`
`compile through：g++ `pkg-config --cflags gstreamer-1.0 opencv` -fPIC -c test.cpp  `pkg-config --libs gstreamer-1.0 gobject-2.0 glib-2.0 opencv `  -lgstapp-1.0 -lpthread -std=c++11

 g++ `pkg-config --cflags gstreamer-1.0 opencv` -fPIC -c gst_appsink_opencv.cpp  `pkg-config --libs gstreamer-1.0 gobject-2.0 glib-2.0 opencv `  -lgstapp-1.0 -lpthread -std=c++11

 g++ `pkg-config --cflags gstreamer-1.0 opencv` -fPIC -o test.o gst_appsink_opencv.o  
test  `pkg-config --libs gstreamer-1.0 gobject-2.0 glib-2.0 opencv `  -lgstapp-1.0 -lpthread -std=c++11`

compile successed。

when I   ./test    it return error: ---- Segmentation fault (core dumped)

**Comment by Myzhar** [comment]
I tested it with OpenCV 2.4.13. Maybe that you must change something to let it work with OpenCV3.
Try to debug the application step by step and try to understand where the segmentation fault happens.
Check also if the line
""video/x-raw,format=I420,framerate=30/1,width=1280,height=720 ! "
is good for your webcam
you can check it launching this command in a Linux console:
"gst-launch-1.0 v4l2src device=/dev/video0 ! 'video/x-raw,format=I420,framerate=30/1,width=1280,height=720' ! videoconvert ! queue ! autovideosink"
